### ISSUE TITLE
Empty message oneOf array throws undefined error

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/playground#94]
#### Describe the bug
Empty `oneOf` array as message should be allowed but throws `undefined` exception.

#### How to Reproduce
Use the following document:
```yaml
asyncapi: 2.0.0
info:
  title: test
  version: 0.0.1
channels:
  'test':
    publish:
      message:
        oneOf: []
```

#### Expected behavior
Not to throw an error, since this is technically a correct document.
